system:
  db_agent_file: agent.db
  db_core_file: core.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.fit2cloud.com/1panel/package
  app_repo: https://apps-assets.fit2cloud.com
  username: admin
  password: admin

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
