version: '3'
services:
  openresty1.21.4:
    image: openresty/openresty:1.21.4.1-3-alpine
    restart: always
    network_mode: host
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./log:/var/log/nginx
      - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
      - ./www:/www
      - ./root:/usr/share/nginx/html
    labels:
      createdBy: "apps"
