version: '3'

services:
  mysql8.0:
    image: mysql:8.0.30
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    networks:
      - 1panel
    ports:
      - ${PORT}:3306
    volumes:
      - ./data/:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./log:/var/log/mysql

networks:
  1panel:
    external: true