version: '3'
services:
    1panel_minio:
      image: minio/minio:RELEASE.2022-08-13T21-54-44Z
      container_name: 1panel_minio
      ports:
        - ${PANEL_APP_PORT_HTTP}:9000
        - ${PORT_API}:9001
      restart: always
      command: server /data --console-address :9000 --address :9001
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      logging:
        options:
          max-size: "5M"
          max-file: "10"
        driver: json-file
      networks:
        - 1panel
      volumes:
        - ./data:/data
      labels:
        createdBy: "Apps"

networks:
  1panel:
    external: true