version: '3'
services:
  redis-7.0.5:
    image: redis:7.0.5
    restart: always
    networks:
      - 1panel
    ports:
      - ${PANEL_APP_PORT_HTTP}:6379
    command: redis-server  /etc/redis/redis.conf --requirepass ${PANEL_DB_ROOT_PASSWORD}
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./logs:/logs
    labels:
      createdBy: "Apps"

networks:
  1panel:
    external: true