name: BUG 提交
description: 提交产品缺陷帮助我们更好的改进
title: "[BUG]"
labels: "类型: 缺陷"
assignees: wanghe-fit2cloud
body:
  - type: markdown
    id: contacts_title
    attributes:
      value: "## 联系方式"
  - type: input
    id: contacts
    validations:
      required: false
    attributes:
      label: "联系方式"
      description: "可以快速联系到您的方式：交流群号及昵称、邮箱等"
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "1Panel 版本"
      description: "登录 1Panel Web 控制台，在页面右下角查看当前版本。"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: "问题描述"
      description: "简要描述您碰到的问题"
    validations:
      required: true
  - type: textarea
    id: how-happened
    attributes:
      label: "重现步骤"
      description: "如果操作可以重现该问题"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: "期待的正确结果"
  - type: textarea
    id: logs
    attributes:
      label: "相关日志输出"
      description: "请复制并粘贴任何相关的日志输出。 这将自动格式化为代码，因此无需反引号。"
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
