name: 需求建议
description: 提出针对本项目的想法和建议
title: "[FEATURE]"
labels: enhancement
assignees: wanghe-fit2cloud
body:
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "1Panel 版本"
      description: "可通过系统右上角下拉菜单中的`关于`选项，或查看安装目录中的 version 文件获取。"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: description
    attributes:
      label: "请描述您的需求或者改进建议"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "请描述你建议的实现方案"
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"