name: 问题咨询
description: 提出针对本项目安装部署、使用及其他方面的相关问题
title: "[QUESTION]"
labels: question
assignees: wanghe-fit2cloud
body:
  - type: textarea
    id: description
    attributes:
      label: "请描述您的问题"
    validations:
      required: true