package service

import (
	"fmt"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/1Panel-dev/1Panel/agent/app/model"
	"github.com/1Panel-dev/1Panel/agent/constant"
)

const (
	// nginxHTTPConfDir holds http-context directives generated by 1Panel.
	// load_module is a main-context directive and therefore lives in
	// modules-enabled, which cannot host http-context directives such as
	// "brotli on". The directory is included by nginx.conf before conf.d so
	// that per-site configuration keeps overriding these defaults.
	nginxHTTPConfDir = "http.d"

	nginxHTTPConfigPrefix = "1panel-http-"
	nginxHTTPConfigHeader = "# Managed by 1Panel. Manual changes will be overwritten.\n"
)

// nginxHTTPDirective is a single http-context directive rendered into a
// managed file.
type nginxHTTPDirective struct {
	Name   string
	Params []string
}

func (d nginxHTTPDirective) render() string {
	if len(d.Params) == 0 {
		return d.Name + ";"
	}
	return d.Name + " " + strings.Join(d.Params, " ") + ";"
}

// nginxHTTPConfigSupported reports whether the installed OpenResty exposes the
// managed http.d directory. Installations created before http.d was introduced
// have no such directory and no include for it, so writing files there would
// silently have no effect.
func nginxHTTPConfigSupported(install model.AppInstall) bool {
	info, err := os.Stat(nginxHTTPConfigDir(install))
	return err == nil && info.IsDir()
}

func nginxHTTPConfigDir(install model.AppInstall) string {
	return path.Join(install.GetPath(), nginxModuleConfDir, nginxHTTPConfDir)
}

func nginxHTTPConfigFileName(order int, name string) string {
	return fmt.Sprintf("%s%04d-%s.conf", nginxHTTPConfigPrefix, order, nginxModulePathName(name))
}

// renderNginxHTTPConfig builds the content of a managed http.d file.
func renderNginxHTTPConfig(directives []nginxHTTPDirective) []byte {
	var content strings.Builder
	content.WriteString(nginxHTTPConfigHeader)
	for _, directive := range directives {
		content.WriteString(directive.render())
		content.WriteString("\n")
	}
	return []byte(content.String())
}

var nginxHTTPDirectiveRe = regexp.MustCompile(`^[ \t]*([a-z_][a-z0-9_]*)[ \t]+([^;]*);[ \t]*$`)

// readNginxHTTPDirectives parses a managed file back into directive values.
// A missing or unreadable file yields no directives, which makes callers fall
// back to their defaults.
func readNginxHTTPDirectives(filePath string) map[string][]string {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil
	}
	directives := make(map[string][]string)
	for _, line := range strings.Split(string(content), "\n") {
		match := nginxHTTPDirectiveRe.FindStringSubmatch(line)
		if match == nil {
			continue
		}
		directives[match[1]] = strings.Fields(match[2])
	}
	return directives
}

// snapshotManagedNginxHTTPConfigs captures every managed file so a failed
// nginx -t can be rolled back.
func snapshotManagedNginxHTTPConfigs(configDir string) (nginxModuleConfigSnapshot, error) {
	snapshot := make(nginxModuleConfigSnapshot)
	entries, err := os.ReadDir(configDir)
	if err != nil {
		if os.IsNotExist(err) {
			return snapshot, nil
		}
		return nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), nginxHTTPConfigPrefix) {
			continue
		}
		content, readErr := os.ReadFile(path.Join(configDir, entry.Name()))
		if readErr != nil {
			return nil, readErr
		}
		snapshot[entry.Name()] = content
	}
	return snapshot, nil
}

// applyManagedNginxHTTPConfigs writes the desired managed files and removes
// managed files that are no longer wanted. Files not carrying the managed
// prefix are never touched.
func applyManagedNginxHTTPConfigs(configDir string, desired map[string][]byte) error {
	if err := os.MkdirAll(configDir, constant.DirPerm); err != nil {
		return err
	}
	entries, err := os.ReadDir(configDir)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(desired))
	for fileName := range desired {
		names = append(names, fileName)
	}
	sort.Strings(names)
	for _, fileName := range names {
		tmpPath := path.Join(configDir, "."+fileName+".tmp")
		if err = os.WriteFile(tmpPath, desired[fileName], constant.FilePerm); err != nil {
			return err
		}
		if err = os.Rename(tmpPath, path.Join(configDir, fileName)); err != nil {
			return err
		}
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), nginxHTTPConfigPrefix) {
			continue
		}
		if _, ok := desired[entry.Name()]; !ok {
			if err = os.Remove(path.Join(configDir, entry.Name())); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}
