package constant

const (
	StatusRunning        = "Running"
	StatusCanceled       = "Canceled"
	StatusDone           = "Done"
	StatusWaiting        = "Waiting"
	StatusSuccess        = "Success"
	StatusFailed         = "Failed"
	StatusUploading      = "Uploading"
	StatusEnable         = "Enable"
	StatusDisable        = "Disable"
	StatusNone           = "None"
	StatusDeleted        = "Deleted"
	StatusExecuting      = "Executing"
	StatusBuilding       = "Building"
	StatusReCreating     = "Recreating"
	StatusStopped        = "Stopped"
	StatusCreating       = "Creating"
	StatusStartErr       = "StartErr"
	StatusNormal         = "Normal"
	StatusError          = "Error"
	StatusStarting       = "Starting"
	StatusRestarting     = "ReStarting"
	StatusUnHealthy      = "UnHealthy"
	StatusInstalling     = "Installing"
	StatusDownloadErr    = "DownloadErr"
	StatusUpgrading      = "Upgrading"
	StatusUpgradeErr     = "UpgradeErr"
	StatusRebuilding     = "Rebuilding"
	StatusSyncing        = "Syncing"
	StatusSyncSuccess    = "SyncSuccess"
	StatusPaused         = "Paused"
	StatusUpErr          = "UpErr"
	StatusInstallErr     = "InstallErr"
	StatusUninstalling   = "Uninstalling"
	StatusWaitingRestart = "WaitingRestart"

	OrderDesc = "descending"
	OrderAsc  = "ascending"
)
