system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://1panel.oss-cn-hangzhou.aliyuncs.com/package

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  log_backup: 10
