gzip                on;
gzip_vary           on;
gzip_min_length     1k;
gzip_buffers        4 16k;
gzip_http_version   1.1;
gzip_comp_level     5;
gzip_proxied        any;
gzip_types          text/plain text/css text/xml text/javascript application/json application/ld+json application/javascript application/x-javascript application/xml application/xhtml+xml application/rss+xml application/atom+xml application/wasm image/svg+xml font/ttf font/otf;
