location ~ ^/(?<site_path>.*/)?{{.imgage}}/(?<path>.+)\.(?<ext>jpe?g|png|gif)$ {
    set $original_uri "$uri";
    add_header Vary Accept;
    add_header Cache-Control "private";
    add_header X-Debug-WebP-Check "$host${site_path}webpdir/$path.$ext$webp_suffix" always;
    add_header X-Debug-Uriwebp "$host$original_uri" always;
    add_header X-Debug-Uri "$uri" always;
    expires 365d;
    proxy_intercept_errors on; # 拦截 404
    error_page 404 = @fallback;
    proxy_pass http://{{.proxy_url}}/${site_path}webpdir/$path.$ext$webp_suffix;

}

location @fallback {
    proxy_pass http://{{.proxy_url}}$original_uri;
}