<template>
    <div v-loading="loading">
        <LayoutContent :title="zone.name" v-if="zone.id">
            <template #leftToolBar>
                <el-button type="primary" @click="onCreateRecord">
                    {{ $t('dns.createRecord') }}
                </el-button>
                <el-button @click="onSync" :loading="syncLoading" plain>
                    {{ $t('dns.syncZone') }}
                </el-button>
            </template>
            <template #rightToolBar>
                <el-select v-model="filterType" @change="search()" class="p-w-200 mr-2" clearable>
                    <el-option label="All" value="" />
                    <el-option v-for="t in recordTypes" :key="t" :label="t" :value="t" />
                </el-select>
                <TableSearch @search="search()" v-model:searchName="searchName" />
                <TableRefresh @search="search()" />
            </template>
            <template #main>
                <!-- Zone info -->
                <el-card class="mb-4">
                    <el-descriptions :column="4" border size="small">
                        <el-descriptions-item :label="$t('dns.zoneType')">
                            <el-tag v-if="zone.type === 'Native'" type="primary">{{ $t('dns.native') }}</el-tag>
                            <el-tag v-else type="warning">{{ $t('dns.slave') }}</el-tag>
                        </el-descriptions-item>
                        <el-descriptions-item :label="$t('dns.soaPrimary')">{{ zone.soaPrimary }}</el-descriptions-item>
                        <el-descriptions-item :label="$t('dns.soaEmail')">{{ zone.soaEmail }}</el-descriptions-item>
                        <el-descriptions-item :label="$t('dns.defaultTTL')">{{ zone.defaultTTL }}s</el-descriptions-item>
                    </el-descriptions>
                </el-card>

                <!-- Records table -->
                <ComplexTable
                    :pagination-config="paginationConfig"
                    @search="search"
                    :data="records"
                >
                    <el-table-column :label="$t('dns.name')" prop="name" min-width="200" show-overflow-tooltip />
                    <el-table-column :label="$t('dns.recordType')" prop="type" min-width="80">
                        <template #default="{ row }">
                            <el-tag size="small">{{ row.type }}</el-tag>
                        </template>
                    </el-table-column>
                    <el-table-column :label="$t('dns.content')" prop="content" min-width="200" show-overflow-tooltip />
                    <el-table-column :label="$t('dns.ttl')" prop="ttl" min-width="80" />
                    <el-table-column :label="$t('dns.priority')" prop="priority" min-width="80">
                        <template #default="{ row }">
                            {{ row.type === 'MX' || row.type === 'SRV' ? row.priority : '-' }}
                        </template>
                    </el-table-column>
                    <el-table-column :label="$t('dns.status')" prop="disabled" min-width="80">
                        <template #default="{ row }">
                            <el-tag v-if="!row.disabled" type="success" size="small">{{ $t('dns.enabled') }}</el-tag>
                            <el-tag v-else type="info" size="small">{{ $t('dns.disabled') }}</el-tag>
                        </template>
                    </el-table-column>
                    <el-table-column min-width="60">
                        <template #default="{ row }">
                            <el-tag v-if="row.autoGen" type="warning" size="small">{{ $t('dns.autoGenerated') }}</el-tag>
                        </template>
                    </el-table-column>
                    <fu-table-operations
                        :ellipsis="10"
                        :buttons="buttons"
                        :label="$t('commons.table.operate')"
                        fixed="right"
                        fix
                    />
                </ComplexTable>
            </template>
        </LayoutContent>

        <RecordCreate ref="recordCreateRef" :zone-id="zone.id" :zone-name="zone.name" :default-ttl="zone.defaultTTL" @search="search()" />
        <OpDialog ref="opRef" @search="search()" />
    </div>
</template>

<script lang="ts" setup>
import { onMounted, reactive, ref } from 'vue';
import { useRoute } from 'vue-router';
import { getDnsZone, searchDnsRecords, syncDnsZone, deleteDnsRecord } from '@/api/modules/dns';
import { Dns } from '@/api/interface/dns';
import RecordCreate from './record-create.vue';
import i18n from '@/lang';
import { MsgSuccess } from '@/utils/message';

const route = useRoute();
const loading = ref(false);
const syncLoading = ref(false);
const searchName = ref('');
const filterType = ref('');
const recordCreateRef = ref();
const opRef = ref();

const recordTypes = ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS', 'SRV', 'CAA', 'SOA'];

const zone = ref<Dns.ZoneRes>({
    id: 0,
    name: '',
    type: 'Native',
    masterIP: '',
    soaPrimary: '',
    soaEmail: '',
    soaRefresh: 0,
    soaRetry: 0,
    soaExpire: 0,
    soaTTL: 0,
    defaultTTL: 3600,
    status: '',
    pdnsID: '',
    recordCount: 0,
});

const records = ref<Dns.RecordRes[]>([]);

const paginationConfig = reactive({
    cacheSizeKey: 'dns-record-page-size',
    currentPage: 1,
    pageSize: Number(localStorage.getItem('dns-record-page-size')) || 20,
    total: 0,
});

const buttons = [
    {
        label: i18n.global.t('commons.button.edit'),
        click: (row: Dns.RecordRes) => {
            onEditRecord(row);
        },
    },
    {
        label: i18n.global.t('commons.button.delete'),
        click: (row: Dns.RecordRes) => {
            onDeleteRecord(row);
        },
    },
];

const loadZone = async () => {
    const id = Number(route.params.id);
    if (!id) return;
    const res = await getDnsZone(id);
    zone.value = res.data;
};

const search = async () => {
    if (!zone.value.id) return;
    loading.value = true;
    try {
        const req: Dns.RecordSearch = {
            zoneID: zone.value.id,
            type: filterType.value || undefined,
            info: searchName.value || undefined,
            page: paginationConfig.currentPage,
            pageSize: paginationConfig.pageSize,
        };
        const res = await searchDnsRecords(req);
        records.value = res.data.items || [];
        paginationConfig.total = res.data.total;
    } finally {
        loading.value = false;
    }
};

const onCreateRecord = () => {
    recordCreateRef.value.acceptParams({ mode: 'create' });
};

const onEditRecord = (row: Dns.RecordRes) => {
    recordCreateRef.value.acceptParams({ mode: 'edit', form: { ...row } });
};

const onDeleteRecord = (row: Dns.RecordRes) => {
    opRef.value.acceptParams({
        title: i18n.global.t('dns.deleteRecord'),
        names: [row.name],
        msg: i18n.global.t('dns.deleteRecordHelper'),
        api: deleteDnsRecord,
        params: { id: row.id },
    });
};

const onSync = async () => {
    syncLoading.value = true;
    try {
        await syncDnsZone({ id: zone.value.id });
        MsgSuccess(i18n.global.t('commons.msg.operationSuccess'));
        await search();
    } finally {
        syncLoading.value = false;
    }
};

onMounted(async () => {
    await loadZone();
    await search();
});
</script>
