on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

name: Build Test

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.2'
      - name: Build Web
        id: build_frontend
        run: |
          cd frontend && npm install && npm run build:pro
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Server
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --clean