name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  issue-close-require:
    runs-on: ubuntu-latest
    steps:
      - name: needs more info
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issues'
          labels: '状态:待反馈'
          inactive-day: 30
          body: |
            您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
