name: Typos Check
on: pull_request
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
    - name: Check spelling
      uses: crate-ci/typos@3bc303c295c081add5df4a4d52a1e117f2fb2dce # master